name-template: 'ðŸ’¡ v$NEXT_MINOR_VERSION'
tag-template: '$NEXT_MINOR_VERSION'
categories:
  - title: 'ðŸš€ ê¸°ëŠ¥ ì¶”ê°€'
    label: 
      - 'íŒ¨ì¹˜ ë…¸íŠ¸'
      - 'ê¸°ëŠ¥ ì¶”ê°€'
  - title: 'ðŸš¨ ë²„ê·¸ ìˆ˜ì •'
    label:
      - 'íŒ¨ì¹˜ ë…¸íŠ¸'
      - 'ë²„ê·¸'
change-template: '- $TITLE #$NUMBER @$AUTHOR '
template: |
  $CHANGES

autolabeler:
  - label: 'ê¸°ëŠ¥ ì¶”ê°€'
    body:
      - '/\*ê¸°ëŠ¥ì¶”ê°€\*'
  - label: 'íŒ¨ì¹˜ ë…¸íŠ¸'
    body:
      - '/\*íŒ¨ì¹˜ë…¸íŠ¸\*'
  - label: 'ë²„ê·¸'
    body:
      - '/\*ë²„ê·¸\*'